version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: access_control_dev_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: access_control_dev
      POSTGRES_USER: access_control_user
      POSTGRES_PASSWORD: secure_password_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - access_control_network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: access_control_dev_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis_password_2024
    volumes:
      - redis_data:/data
    networks:
      - access_control_network

  # PgAdmin (opcional para gestión de BD)
  pgadmin:
    image: dpage/pgadmin4
    container_name: access_control_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - access_control_network

volumes:
  postgres_data:
  redis_data:

networks:
  access_control_network:
    driver: bridge